spring.application.name=patient-service
server.port=4000

## H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
## H2 Datasource
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=admin_viewer
#spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

billing.service.address=billing-service
billing.service.grpc.port=9001